### PR TITLE
fix: json protocols with HttpBody

### LINKED ISSUE #541: `DynamoDbClient` `listTables` method doesn't work
## Description
When calling `listTables` method on `DynamoDbClient` the following error occurs:
`service(AWSDynamoDB.ListTablesOutputError.unknown(AWSClientRuntime.UnknownAWSHttpServiceError(_isThrottling: false, _statusCode: Optional(http_status_400), _headers: Optional(Date: Wed, 16 Feb 2022 07:37:29 GMT, `

## Environment

* AWS Swift SDK version used: 0.1.3
* Operating System and version (iOS/macOS/Linux): iOS 15.2
* Xcode version (if applicable): Version 13.2.1 (13C100)

## Reproduction Steps

Code snippet:
```swift
let database = Database()
database.listAllTables()

class Database {
    
    private lazy var config = try! DynamoDbClient.DynamoDbClientConfiguration(region: "eu-north-1")
    private lazy var client = DynamoDbClient(config: config)
    
   func listAllTables() {
        client.listTables(input: ListTablesInput()) { result in
            switch(result) {
            case .success(let response):
                guard let namesOfTables = response.tableNames else {
                    return
                }
                for currName in namesOfTables {
                    print("Table name is \(currName)")
                }
            case .failure(let err):
                print(err)
            }
        }
    }
}
```

Logs:
```
2022-02-16T10:50:15+0300 info DynamoDbClient : Request: POST https:443 
 Path: /, 
 x-amz-user-agent: aws-sdk-swift/1.0, 
X-Amz-Target: DynamoDB_20120810.ListTables, 
Authorization: AWS4-HMAC-SHA256 Credential=<HIDDEN>/20220216/eu-north-1/dynamodb/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target;x-amz-user-agent, Signature=<HIDDEN>, 
Host: dynamodb.eu-north-1.amazonaws.com, 
X-Amz-Date: 20220216T075015Z, 
Content-Type: application/x-amz-json-1.0, 
Content-Length: 0, 
User-Agent: aws-sdk-swift/1.0 api/dynamodb/1.0 os/iOS/15.2.0 lang/swift/5.5 
 Optional([])
2022-02-16T10:50:15+0300 info CRTClientEngine : Creating connection pool for Optional("https://dynamodb.eu-north-1.amazonaws.com:443/?")with max connections: 50
2022-02-16T10:50:15+0300 info CRTClientEngine : Connection was acquired to: Optional("https://dynamodb.eu-north-1.amazonaws.com:443/?")
2022-02-16T10:50:15+0300 info CRTClientEngine : headers were received
2022-02-16T10:50:15+0300 info CRTClientEngine : headers were received
2022-02-16T10:50:15+0300 info CRTClientEngine : headers were received
2022-02-16T10:50:15+0300 info CRTClientEngine : headers were received
2022-02-16T10:50:15+0300 info CRTClientEngine : headers were received
2022-02-16T10:50:15+0300 info CRTClientEngine : headers were received
2022-02-16T10:50:15+0300 info CRTClientEngine : headers were received
2022-02-16T10:50:15+0300 info CRTClientEngine : header block is done
2022-02-16T10:50:15+0300 info CRTClientEngine : incoming data
2022-02-16T10:50:16+0300 info CRTClientEngine : stream completed
2022-02-16T10:50:16+0300 info CRTClientEngine : Future of response came back with success
service(AWSDynamoDB.ListTablesOutputError.unknown(AWSClientRuntime.UnknownAWSHttpServiceError(_isThrottling: false, _statusCode: Optional(http_status_400), _headers: Optional(Date: Wed, 16 Feb 2022 07:50:16 GMT, 
x-amz-crc32: 3948637019, 
Connection: keep-alive, 
Content-Type: application/x-amz-json-1.0, 
Server: Server, 
x-amzn-RequestId: PK6S1JTDDPLKEVA64OAVRE0UPBVV4KQNSO5AEMVJF66Q9ASUAAJG, 
Content-Length: 60), _message: nil, _requestID: Optional("PK6S1JTDDPLKEVA64OAVRE0UPBVV4KQNSO5AEMVJF66Q9ASUAAJG"), _retryable: false, _type: ClientRuntime.ErrorType.unknown)), 
Status Code: http_status_400 
 Date: Wed, 16 Feb 2022 07:50:16 GMT, 
x-amz-crc32: 3948637019, 
Connection: keep-alive, 
Content-Type: application/x-amz-json-1.0, 
Server: Server, 
x-amzn-RequestId: PK6S1JTDDPLKEVA64OAVRE0UPBVV4KQNSO5AEMVJF66Q9ASUAAJG, 
Content-Length: 60)
```

I made the same request using **aws-cli**:
```
POST / HTTP/1.1
Host: dynamodb.eu-north-1.amazonaws.com
Accept-Encoding: identity
X-Amz-Target: DynamoDB_20120810.ListTables
Content-Type: application/x-amz-json-1.0
User-Agent: aws-cli/2.4.18 Python/3.8.8 Darwin/21.3.0 exe/x86_64 prompt/off command/dynamodb.list-tables
X-Amz-Date: 20220216T075355Z
Authorization: AWS4-HMAC-SHA256 Credential=<HIDDEN>/20220216/eu-north-1/dynamodb/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=<HIDDEN>
Content-Length: 2

{}
```

The difference in HTTP RAW Requests is here:

**aws-cli:**
Content-Length: 2, 
Body: {}

**aws-sdk-swift:**
Content-Length: 0, 
Body:  Optional([])

Content-Length must be 2 and the body must be `{}`

## Observed Behavior
The following error occurs:
`service(AWSDynamoDB.ListTablesOutputError.unknown(AWSClientRuntime.UnknownAWSHttpServiceError(_isThrottling: false, _statusCode: Optional(http_status_400), _headers: Optional(Date: Wed, 16 Feb 2022 07:37:29 GMT, `

## Expected Behavior
A list of tables should appears in the output.

### PR DESCRIPTION
**Pull request by kneekey23**
## Issue \#

This closes #541 and #524 and fixes an issue where we were not sending an empty json object across the wire for aws json protocols nor were we generating protocol tests correctly to test for it.

Corresponding PR: https://github.com/awslabs/smithy-swift/pull/408

## Conventional Commits

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: AWSClientRuntime/Sources/Middlewares/EndpointResolverMiddleware.swift [hunk 1]
```diff
@@ -19,51 +19,52 @@ public struct EndpointResolverMiddleware<OperationStackOutput: HttpResponseBindi
...
+          Self.MOutput == H.Output,
+          Self.Context == H.Context {
+              
+              guard let region = context.getRegion(), !region.isEmpty else {
+                  throw SdkError<OperationStackError>.client(ClientError.unknownError(("Region is unable to be resolved")))
+              }
+              var awsEndpoint: AWSEndpoint
+              do {
+                  awsEndpoint = try endpointResolver.resolve(serviceId: serviceId,
+                                                             region: region)
```
Comment (rcoh) [inline AWSClientRuntime/Sources/Middlewares/EndpointResolverMiddleware.swift:32]: intentional change to endpoint handling? This code looks like it maintains the previous behavior?

**Review by rcoh — APPROVED** [review]

File: AWSClientRuntime/Sources/Middlewares/EndpointResolverMiddleware.swift (hunk 1 above)
Comment (kneekey23) [reply AWSClientRuntime/Sources/Middlewares/EndpointResolverMiddleware.swift:32]: ya we weren't actually bubbling up the correct error before with the way the code was written. this is a minor change that keeps same beahvior but now the correct error gets bubbled up to the caller. with the previous code, every error looked like an endpoint error when in reality it wasn't :)
