### PR TITLE
fix! Converts Expires members in S3 output structures to String shape

### LINKED ISSUE #200: S3 Expires top level output member should be a string instead timestamp
aws/aws-sdk-go@5bdeab7

*internal id*: 176722195

### PR DESCRIPTION
**Pull request by epau**
## Issue \#
fixes #200 

## Description of changes
This PR adds a customization during codegen, that will convert members to String shape. 
This is restricted to members named "Expires" on "Output" structures in the S3 service.

## Conventional Commits

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/s3/S3Expires.kt [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+    override fun enabledForService(model: Model, settings: SwiftSettings): Boolean {
+        return model.expectShape<ServiceShape>(settings.service).isS3
+    }
+
+    override fun preprocessModel(model: Model, settings: SwiftSettings): Model {
+        // Find all the members named "Expires" in all of the output structures
+        // and change their shape from `Timestamp` to `String`
+        val updates = model.structureShapes
+            .filter { it.defaultName().endsWith("Output") }
```
Comment (epau) [inline codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/s3/S3Expires.kt:21]: So this is indeed the suffix we want to check for, but this currently is failing for tests (although it works as we want when generating the models). All output models are given a `Response` suffix but the timing (and perhaps other factors) are different when executed for tests. I need to dig in to what exactly is going on in our test flow to get tests passing.

File: codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/TestContextGenerator.kt [hunk 2]
```diff
@@ -36,7 +36,6 @@ class TestContextGenerator {
             val service = model.getShape(ShapeId.from(serviceShapeIdWithNamespace)).get().asServiceShape().get()
             val settings = buildDefaultSwiftSettingsObjectNode(serviceShapeIdWithNamespace)
             val swiftSettings = SwiftSettings.from(model, settings)
-            model = AddOperationShapes.execute(model, swiftSettings.getService(model), swiftSettings.moduleName)
```
Comment (epau) [inline codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/TestContextGenerator.kt:39]: This is not necessary and is inconsistent with how this is performed in release.
By calling this here, we end up adding operation shapes before any of the integrations are executed. In release, we execute the integrations first, then add our operation shapes. By removing this line, we make our testing environment more consistent with our releases.

This logic is perform within `SwiftCodegenPlugin().execute(pluginContext)` which occurs a few lines below this.

**Review by jbelkins — APPROVED** [review]
